# Generated by Django 5.1.5 on 2025-06-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_alter_studentclass_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='section',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
